"""add parent_id to inquiries

Revision ID: 42291e80ee26
Revises: 7e94001051b2
Create Date: 2026-09-15 11:54:19.019865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '42291e80ee26'
down_revision = '7e94001051b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_bot_inquiries', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_tg_bot_inquiries_parent_id'), 'tg_bot_inquiries', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tg_bot_inquiries_parent_id'), table_name='tg_bot_inquiries')
    op.drop_column('tg_bot_inquiries', 'parent_id')
    # ### end Alembic commands ###
