"""add_broadcast_table

Revision ID: 7e94001051b2
Revises: ed32278d7e5f
Create Date: 2026-09-15 11:48:03.889759

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e94001051b2'
down_revision = 'ed32278d7e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bot_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('from_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('target_filter', sa.VARCHAR(length=100), nullable=False),
    sa.Column('button_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('button_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('total_target', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'completed', 'cancelled', name='broadcaststatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_broadcasts_admin_id'), 'tg_bot_broadcasts', ['admin_id'], unique=False)
    op.alter_column('tg_bot_inquiries', 'answer_mediatype',
               existing_type=mysql.ENUM('text', 'voice', 'video_note', 'video', 'document', 'photo'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_inquiries', 'answer_mediatype',
               existing_type=mysql.ENUM('text', 'voice', 'video_note', 'video', 'document', 'photo'),
               nullable=True)
    op.drop_index(op.f('ix_tg_bot_broadcasts_admin_id'), table_name='tg_bot_broadcasts')
    op.drop_table('tg_bot_broadcasts')
    # ### end Alembic commands ###
