"""add_appointments_official_lawyers_and_inquiry_rating

Revision ID: 8d4acce15674
Revises: e1a2b3c4d5e6
Create Date: 2026-09-15 11:27:15.414505

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d4acce15674'
down_revision = 'e1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bot_official_lawyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_official_lawyers_user_id'), 'tg_bot_official_lawyers', ['user_id'], unique=True)
    op.create_table('tg_bot_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('lawyer_id', sa.BigInteger(), nullable=True),
    sa.Column('group_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'completed', 'cancelled', name='appointmentstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tg_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bot_appointments_lawyer_id'), 'tg_bot_appointments', ['lawyer_id'], unique=False)
    op.create_index(op.f('ix_tg_bot_appointments_user_id'), 'tg_bot_appointments', ['user_id'], unique=False)
    op.add_column('tg_bot_inquiries', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('tg_bot_inquiries', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('tg_bot_inquiries', sa.Column('rated_at', sa.DateTime(), nullable=True))
    op.alter_column('tg_bot_users', 'language',
               existing_type=mysql.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'uz'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_bot_users', 'language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'uz'"))
    op.drop_column('tg_bot_inquiries', 'rated_at')
    op.drop_column('tg_bot_inquiries', 'feedback')
    op.drop_column('tg_bot_inquiries', 'rating')
    op.drop_index(op.f('ix_tg_bot_appointments_user_id'), table_name='tg_bot_appointments')
    op.drop_index(op.f('ix_tg_bot_appointments_lawyer_id'), table_name='tg_bot_appointments')
    op.drop_table('tg_bot_appointments')
    op.drop_index(op.f('ix_tg_bot_official_lawyers_user_id'), table_name='tg_bot_official_lawyers')
    op.drop_table('tg_bot_official_lawyers')
    # ### end Alembic commands ###
