"""add_multimodal_and_schedule_fields

Revision ID: ed32278d7e5f
Revises: 8d4acce15674
Create Date: 2026-09-15 11:40:22.699251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ed32278d7e5f'
down_revision = '8d4acce15674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_bot_appointments', sa.Column('media_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('media_file_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('media_name', sa.VARCHAR(length=255), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('media_meta', sa.Text(), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('meeting_link', sa.VARCHAR(length=500), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('tg_bot_appointments', sa.Column('reminder_sent', sa.Boolean(), nullable=False))
    op.add_column('tg_bot_official_lawyers', sa.Column('working_days', sa.VARCHAR(length=50), nullable=False))
    op.add_column('tg_bot_official_lawyers', sa.Column('start_hour', sa.Integer(), nullable=False))
    op.add_column('tg_bot_official_lawyers', sa.Column('end_hour', sa.Integer(), nullable=False))
    op.add_column('tg_bot_official_lawyers', sa.Column('slot_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_bot_official_lawyers', 'slot_duration')
    op.drop_column('tg_bot_official_lawyers', 'end_hour')
    op.drop_column('tg_bot_official_lawyers', 'start_hour')
    op.drop_column('tg_bot_official_lawyers', 'working_days')
    op.drop_column('tg_bot_appointments', 'reminder_sent')
    op.drop_column('tg_bot_appointments', 'cancellation_reason')
    op.drop_column('tg_bot_appointments', 'meeting_link')
    op.drop_column('tg_bot_appointments', 'media_meta')
    op.drop_column('tg_bot_appointments', 'media_name')
    op.drop_column('tg_bot_appointments', 'media_file_id')
    op.drop_column('tg_bot_appointments', 'media_type')
    # ### end Alembic commands ###
